
export const SET_USER = "SET_USER";

export const FETCH_LOGIN = "FETCH_LOGIN";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
export const FETCH_LOGIN_FAILURE = "FETCH_LOGIN_FAILURE";
export const FETCH_LOGIN_CLEAR = "FETCH_LOGIN_CLEAR";

export const GET_RECENT_COURSES = "GET_RECENT_COURSES";
export const GET_RECENT_COURSES_SUCCESS = "GET_RECENT_COURSES_SUCCESS";
export const GET_RECENT_COURSES_FAILURE = "GET_RECENT_COURSES_FAILURE";

export const ENROLL_COURSE = "ENROLL_COURSE";
export const ENROLL_COURSE_SUCCESS = "ENROLL_COURSE_SUCCESS";
export const ENROLL_COURSE_FAILURE = "ENROLL_COURSE_FAILURE";

export const GET_COURSE_DETAILS = "GET_COURSE_DETAILS";
export const GET_COURSE_DETAILS_SUCCESS = "GET_COURSE_DETAILS_SUCCESS";
export const GET_COURSE_DETAILS_FAILURE = "GET_COURSE_DETAILS_FAILURE";
export const RESET_COURSE_DETAILS = "RESET_COURSE_DETAILS";

export const GET_LESSON_DETAILS = "GET_LESSON_DETAILS";
export const GET_LESSON_DETAILS_SUCCESS = "GET_LESSON_DETAILS_SUCCESS";
export const GET_LESSON_DETAILS_FAILURE = "GET_LESSON_DETAILS_FAILURE";

export const SAVE_LESSON_PROGRESS = "SAVE_LESSON_PROGRESS";
export const SAVE_LESSON_PROGRESS_SUCCESS = "SAVE_LESSON_PROGRESS_SUCCESS";
export const SAVE_LESSON_PROGRESS_FAILURE = "SAVE_LESSON_PROGRESS_FAILURE";
export const RESET_SAVE_LESSON_PROGRESS = "RESET_SAVE_LESSON_PROGRESS";

export const GET_COURSE_LIST = "GET_COURSE_LIST";
export const GET_COURSE_LIST_SUCCESS = "GET_COURSE_LIST_SUCCESS";
export const GET_COURSE_LIST_FAILURE = "GET_COURSE_LIST_FAILURE";

export const SEND_OTP = "SEND_OTP";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const SEND_OTP_FAILURE = "SEND_OTP_FAILURE";
export const FETCH_SEND_OTP_CLEAR = "FETCH_SEND_OTP_CLEAR";

export const OTP_LOGIN = "OTP_LOGIN";
export const OTP_LOGIN_SUCCESS = "OTP_LOGIN_SUCCESS";
export const OTP_LOGIN_FAILURE = "OTP_LOGIN_FAILURE";

export const GET_MY_ACHIEVEMENTS="GET_MY_ACHIEVEMENTS";
export const GET_MY_ACHIEVEMENTS_SUCCESS="GET_MY_ACHIEVEMENTS_SUCCESS";
export const GET_MY_ACHIEVEMENTS_FAILURE="GET_MY_ACHIEVEMENTS_FAILURE";

export const FETCH_NOTIFICATIONS="FETCH_NOTIFICATIONS";
export const FETCH_NOTIFICATIONS_SUCCESS="FETCH_NOTIFICATIONS_SUCCESS";
export const FETCH_NOTIFICATIONS_FAILURE="FETCH_NOTIFICATIONS_FAILURE";

export const DIRT_NOTIFICATION = "DIRT_NOTIFICATION";
export const DIRT_NOTIFICATION_SUCCESS = "DIRT_NOTIFICATION_SUCCESS";
export const DIRT_NOTIFICATION_FAILURE = "DIRT_NOTIFICATION_FAILURE";

export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";
export const CLEAR_NOTIFICATION_SUCCESS = "CLEAR_NOTIFICATION_SUCCESS";
export const CLEAR_NOTIFICATION_FAILURE = "CLEAR_NOTIFICATION_FAILURE";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

export const FORGOT_PASSWORD_MOBILE = "FORGOT_PASSWORD_MOBILE";
export const FORGOT_PASSWORD_MOBILE_SUCCESS = "FORGOT_PASSWORD_MOBILE_SUCCESS";
export const FORGOT_PASSWORD_MOBILE_FAILURE = "FORGOT_PASSWORD_MOBILE_FAILURE";

export const RESET_PASSWORD_MOBILE = "RESET_PASSWORD_MOBILE";
export const RESET_PASSWORD_MOBILE_SUCCESS = "RESET_PASSWORD_MOBILE_SUCCESS";
export const RESET_PASSWORD_MOBILE_FAILURE = "RESET_PASSWORD_MOBILE_FAILURE";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

export const GET_MY_DETAILS = "GET_MY_DETAILS";
export const GET_MY_DETAILS_SUCCESS = "GET_MY_DETAILS_SUCCESS";
export const GET_MY_DETAILS_FAILURE = "GET_MY_DETAILS_FAILURE";

export const ENABLE_AUTO_NAVIGATE = "ENABLE_AUTO_NAVIGATE";
export const DISABLE_AUTO_NAVIGATE = "DISABLE_AUTO_NAVIGATE";

export const GET_COMPLETED_COURSES = "GET_COMPLETED_COURSES";
export const GET_COMPLETED_COURSES_SUCCESS = "GET_COMPLETED_COURSES_SUCCESS";
export const GET_COMPLETED_COURSES_FAILURE = "GET_COMPLETED_COURSES_FAILURE";
